CREATE DATABASE IF NOT EXISTS BdEchoppe;
use BdEchoppe;

DROP TABLE IF EXISTS RESERVATIONCATEGORIE;

DROP TABLE IF EXISTS utilisateur;
CREATE TABLE utilisateur (
    id integer not null auto_increment,
	login varchar(255),
	mot_de_passe varchar(255),
	email varchar(255),
	constraint pk_utilisateur primary key (id)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS administrateur;
CREATE TABLE administrateur (
    id integer not null auto_increment,
	login varchar(255),
	mot_de_passe varchar(255),
	email varchar(255),
	constraint pk_utilisateur primary key (id)
) ENGINE = InnoDB;






CREATE TABLE CLIENT (
	LOGIN VARCHAR(30),
	CONSTRAINT PK_CLIENT PRIMARY KEY (LOGIN), 
	CONSTRAINT FK_UTILISATEUR_CLIENT FOREIGN KEY (LOGIN) REFERENCES UTILISATEUR(LOGIN) ON DELETE CASCADE
) ENGINE = InnoDB; 

CREATE TABLE RESPONSABLEPROG (
	LOGIN VARCHAR(30),
	CONSTRAINT PK_RESPONSABLEPROG PRIMARY KEY (LOGIN),
	CONSTRAINT FK_UTILISATEUR_RESPONSABLEPROG FOREIGN KEY (LOGIN) REFERENCES UTILISATEUR(LOGIN) ON DELETE CASCADE
) ENGINE = InnoDB; 

CREATE TABLE ADMINISTRATEUR (
	LOGIN VARCHAR(30),
	CONSTRAINT PK_ADMINISTRATEUR PRIMARY KEY (LOGIN),
	CONSTRAINT FK_RESPONSABLEPROG_ADMINISTRATEUR FOREIGN KEY (LOGIN) REFERENCES RESPONSABLEPROG(LOGIN) ON DELETE CASCADE
) ENGINE = InnoDB; 

CREATE TABLE SALLE (
	IDSALLE INTEGER NOT NULL AUTO_INCREMENT,
	NOMSALLE VARCHAR(30),
	CONSTRAINT PK_SALLE PRIMARY KEY (IDSALLE)
) ENGINE = InnoDB; 

CREATE TABLE CATEGORIE (
	IDCATEGORIE INTEGER NOT NULL AUTO_INCREMENT,
	NOMCATEGORIE VARCHAR(30) UNIQUE,
	PRIX INTEGER NOT NULL CHECK (PRIX >= 0),
	CONSTRAINT PK_CATEGORIE PRIMARY KEY (IDCATEGORIE) 
) ENGINE = InnoDB; 

CREATE TABLE ZONE (
	IDZONE INTEGER NOT NULL,
	IDSALLE INTEGER NOT NULL,
	IDCATEGORIE INTEGER NOT NULL,
	CONSTRAINT PK_ZONE PRIMARY KEY (IDZONE, IDSALLE),
	CONSTRAINT FK_ZONE_SALLE FOREIGN KEY (IDSALLE) REFERENCES SALLE(IDSALLE) ON DELETE CASCADE,
	CONSTRAINT FK_ZONE_CATEGORIE FOREIGN KEY (IDCATEGORIE) REFERENCES CATEGORIE(IDCATEGORIE) ON DELETE CASCADE,
	CONSTRAINT UNIQUE_SALLECATEGORIE UNIQUE (IDSALLE, IDCATEGORIE)
) ENGINE = InnoDB; 

CREATE TABLE RANG (
	IDRANG VARCHAR(2),
	IDZONE INTEGER NOT NULL,
	IDSALLE INTEGER NOT NULL,
	CONSTRAINT PK_RANG PRIMARY KEY (IDRANG, IDZONE, IDSALLE),
	CONSTRAINT FK_RANG_ZONE FOREIGN KEY (IDZONE, IDSALLE) REFERENCES ZONE(IDZONE, IDSALLE) ON DELETE CASCADE
) ENGINE = InnoDB; 

CREATE TABLE PLACE (
	IDPLACE INTEGER NOT NULL,
	IDRANG VARCHAR(2) NOT NULL,
	IDZONE INTEGER NOT NULL,
	IDSALLE INTEGER NOT NULL,
	CONSTRAINT PK_PLACE PRIMARY KEY (IDPLACE, IDRANG, IDZONE, IDSALLE),
	CONSTRAINT FK_PLACE_RANG FOREIGN KEY (IDRANG, IDZONE, IDSALLE) REFERENCES RANG(IDRANG, IDZONE, IDSALLE) ON DELETE CASCADE
) ENGINE = InnoDB; 

CREATE TABLE SPECTACLE (
	IDSPECTACLE INTEGER NOT NULL AUTO_INCREMENT,
	NOMSPECTACLE VARCHAR(300) NOT NULL,
	CONSTRAINT PK_SPECTACLE PRIMARY KEY (IDSPECTACLE) 
) ENGINE = InnoDB; 

CREATE TABLE REPRESENTATION (
	HEURE DATETIME,
	IDSALLE INTEGER NOT NULL,
	IDSPECTACLE INTEGER NOT NULL,
	CONSTRAINT PK_REPRESENTATION PRIMARY KEY (HEURE, IDSALLE, IDSPECTACLE),
	CONSTRAINT FK_REPRESENTATION_SALLE FOREIGN KEY (IDSALLE) REFERENCES SALLE(IDSALLE) ON DELETE CASCADE,
	CONSTRAINT FK_REPRESENTATION_SPECTACLE FOREIGN KEY (IDSPECTACLE) REFERENCES SPECTACLE(IDSPECTACLE) ON DELETE CASCADE
) ENGINE = InnoDB; 

CREATE TABLE DOSSIER (
	IDDOSSIER INTEGER NOT NULL AUTO_INCREMENT,
	LOGIN VARCHAR(30) NOT NULL,
	HEURE DATETIME NOT NULL,
	IDSPECTACLE INTEGER NOT NULL,
	IDSALLE INTEGER NOT NULL,
	CONSTRAINT PK_DOSSIER PRIMARY KEY (IDDOSSIER),
	CONSTRAINT FK_DOSSIER_CLIENT FOREIGN KEY (LOGIN) REFERENCES CLIENT(LOGIN) ON DELETE CASCADE,
	CONSTRAINT FK_DOSSIER_REPRESENTATION FOREIGN KEY (HEURE, IDSALLE, IDSPECTACLE) REFERENCES REPRESENTATION(HEURE, IDSALLE, IDSPECTACLE) ON DELETE CASCADE
) ENGINE = InnoDB; 

CREATE TABLE TICKET (
	IDTICKET INTEGER NOT NULL AUTO_INCREMENT,
	DATETRANSACTION DATE NOT NULL,
	IDDOSSIER INTEGER NOT NULL,
	IDPLACE INTEGER NOT NULL,
	IDRANG VARCHAR(2) NOT NULL,
	IDZONE INTEGER NOT NULL,
	IDSALLE INTEGER NOT NULL,
	CONSTRAINT PK_TICKET PRIMARY KEY (IDTICKET), 
	CONSTRAINT FK_TICKET_DOSSIER FOREIGN KEY (IDDOSSIER) REFERENCES DOSSIER(IDDOSSIER) ON DELETE CASCADE,
	CONSTRAINT FK_TICKET_PLACE FOREIGN KEY (IDPLACE, IDRANG, IDZONE, IDSALLE) REFERENCES PLACE(IDPLACE, IDRANG, IDZONE, IDSALLE) ON DELETE CASCADE
) ENGINE = InnoDB; 

CREATE TABLE RESERVATION (
	IDRESERVATION INTEGER NOT NULL AUTO_INCREMENT,
	LOGIN VARCHAR(30) NOT NULL,
	HEURE DATETIME NOT NULL,
	IDSALLE INTEGER NOT NULL,
	IDSPECTACLE INTEGER NOT NULL,
	CONSTRAINT UNIQUE_RESERVATION UNIQUE (LOGIN, HEURE, IDSALLE, IDSPECTACLE),
	CONSTRAINT PK_RESERVATION PRIMARY KEY (IDRESERVATION),
	CONSTRAINT FK_RESERVATION_CLIENT FOREIGN KEY (LOGIN) REFERENCES CLIENT(LOGIN) ON DELETE CASCADE,
	CONSTRAINT FK_RESERVATION_REPRESENTATION FOREIGN KEY (HEURE, IDSALLE, IDSPECTACLE) REFERENCES REPRESENTATION(HEURE, IDSALLE, IDSPECTACLE) ON DELETE CASCADE
) ENGINE = InnoDB; 

CREATE TABLE RESERVATIONCATEGORIE (
	IDRESERVATION INTEGER NOT NULL,
	IDCATEGORIE INTEGER NOT NULL,
	NBPLACES INTEGER NOT NULL CHECK (NBPLACES >= 0),
	CONSTRAINT PK_RESERVATIONCATEGORIE PRIMARY KEY (IDRESERVATION, IDCATEGORIE),
	CONSTRAINT FK_RESERVATIONCATEGORIE_RESERVATION FOREIGN KEY (IDRESERVATION) REFERENCES RESERVATION(IDRESERVATION) ON DELETE CASCADE,
	CONSTRAINT FK_RESERVATIONCATEGORIE_CATEGORIE FOREIGN KEY (IDCATEGORIE) REFERENCES CATEGORIE(IDCATEGORIE) ON DELETE CASCADE
) ENGINE = InnoDB;
